#!/bin/sh
ln -s ~/.files/bash/bash_aliases \
      ~/.bash_aliases

ln -s ~/.files/tmux/tmux.conf \
      ~/.tmux.conf

ln -s ~/.files/vim/vimrc \
      ~/.vimrc

# Vim: setup
mkdir -p ~/.vim/after
ln -s ~/.files/vim/after/ftplugin \
      ~/.vim/after/ftplugin

mkdir -p ~/.vim/colors
ln -s ~/.files/vim/colors/melvor.vim \
      ~/.vim/colors/melvor.vim

# Bash: Set up bash links.
# ln -s ~/.files/bash/bash_profile ~/.bash_profile
# ln -s ~/.files/bash/bashrc ~/.bashrc
