#!/bin/sh

ln -s ~/.files/vim/vimrc \
      ~/.vimrc

ln -s ~/.files/tmux/tmux.conf \
      ~/.tmux.conf

ln -s ~/.files/bash/bash_aliases \
      ~/.bash_aliases

# Vim: Setup necessary .vim directories if they don't exist.
# mkdir -p ~/.vim/syntax
# mkdir -p ~/.vim/ftdetect
mkdir -p ~/.vim/after
ln -s ~/.files/vim/after/ftplugin \
      ~/.vim/after/ftplugin

# Bash: Set up bash links.
# ln -s ~/.files/bash/bash_profile ~/.bash_profile
# ln -s ~/.files/bash/bashrc ~/.bashrc
