#!/bin/sh
ln -sf ~/.files/bash/bash_aliases \
      ~/.bash_aliases

ln -sf ~/.files/tmux/tmux.conf \
      ~/.tmux.conf

ln -sf ~/.files/vim/vimrc \
      ~/.vimrc

ln -sf ~/.files/vim/colors \
      ~/.vim

# Bash: Set up bash links.
# ln -s ~/.files/bash/bash_profile ~/.bash_profile
# ln -s ~/.files/bash/bashrc ~/.bashrc
